
### --------------------------------------------------------
###  NextNew: Configuration macro
###  $Id: nexus_NEW.S1.config.mac 10047 2015-01-23 17:07:30Z paola $
### --------------------------------------------------------
/run/verbose 1
/event/verbose 0
/tracking/verbose 0
# GENERATION

/Generator/S1generator/energy 7.20625 eV
/Generator/S1generator/xpos 5.0
/Generator/S1generator/ypos 5.0
/Generator/S1generator/zpos 0.0
/Generator/S1generator/nphotons 1000000
# GEOMETRY
/Geometry/NextNewOpticalGeometry/pressure 15. bar
#/Geometry/NextNewOpticalGeometry/elfield false
# PHYSICS
/control/execute macros/physics/IonizationElectron.mac
/nexus/persistency/outputFile ./S10.next
