### ---------------------------------------------------------
###  This macro simulates Kr83 decays uniformly in the active
###  volume and using the full simulation
### ---------------------------------------------------------


/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# GENERATION
/Generator/SingleParticle/particle gamma
/Generator/SingleParticle/min_energy .1 MeV
/Generator/SingleParticle/max_energy .1 MeV
/Generator/SingleParticle/region AD_HOC
/Geometry/NextNew/specific_vertex_X   0 mm
/Geometry/NextNew/specific_vertex_Y   0 mm
/Geometry/NextNew/specific_vertex_Z  10 mm
/Generator/SingleParticle/momentum_X  0
/Generator/SingleParticle/momentum_Y  0
/Generator/SingleParticle/momentum_Z  1

# ACTIONS
/Actions/AllSteppingAction/select_particle gamma
/Actions/AllSteppingAction/select_volume   ACTIVE

# GEOMETRY
/Geometry/NextNew/pressure 10. bar
/Geometry/PmtR11410/SD_depth 4
/Geometry/PmtR11410/time_binning 100. nanosecond
/Geometry/SiPMSensl/time_binning 1. microsecond
/Geometry/NextNew/elfield false
/Geometry/NextNew/max_step_size 1. mm

# PHYSICS
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

/nexus/persistency/outputFile NEW_gammas_0.1
