### ---------------------------------------------------------
### This init macro simulates geantinos in the NEW geometry
### shot from an specific vertex isotropically
### ---------------------------------------------------------


/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# GENERATION
/Generator/SingleParticle/particle geantino
/Generator/SingleParticle/min_energy 1  eV
/Generator/SingleParticle/max_energy 1 keV
/Generator/SingleParticle/region AD_HOC
/Geometry/NextNew/specific_vertex_X 200 mm
/Geometry/NextNew/specific_vertex_Y  0 mm
/Geometry/NextNew/specific_vertex_Z 10 mm

# ACTIONS
#/Actions/SaveAllSteppingAction/select_particle geantino
/Actions/SaveAllSteppingAction/select_volume EL_GRID
/Actions/SaveAllSteppingAction/select_volume GATE_GRID
#/Actions/SaveAllSteppingAction/select_volume EL_GAP

# GEOMETRY
/Geometry/NextNew/pressure 10. bar
/Geometry/NextNew/real_mesh true
/Geometry/NextNew/mesh_sagging 1 mm
/Geometry/PmtR11410/SD_depth 4

/nexus/persistency/outputFile /home/gonzalo/data/NEXT/geantinos/NEW/mesh_sagg_border_elgap_wire.next
