### ---------------------------------------------------------
###  This macro simulates Kr83 decays uniformly in the active
###  volume and using the full simulation
### ---------------------------------------------------------


/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# GENERATION
/Generator/SingleParticle/particle e-
/Generator/SingleParticle/min_energy 1.59 MeV
/Generator/SingleParticle/max_energy 1.60 MeV
/Generator/SingleParticle/region AD_HOC
/Geometry/NextNew/specific_vertex_X   0 mm
/Geometry/NextNew/specific_vertex_Y   0 mm
/Geometry/NextNew/specific_vertex_Z 250 mm
#/Generator/SingleParticle/momentum_X 1 mm
#/Generator/SingleParticle/momentum_Y 0 mm
#/Generator/SingleParticle/momentum_Z 0 mm

# GEOMETRY
/Geometry/NextNew/pressure 5. bar
/Geometry/NextNew/elfield false
/Geometry/NextNew/max_step_size 1. mm

/Geometry/PmtR11410/SD_depth 4
/Geometry/PmtR11410/time_binning 100. nanosecond
/Geometry/SiPMSensl/time_binning 1. microsecond

# PHYSICS
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

/nexus/persistency/outputFile /home/gonzalo/data/NEXT/zlength/track_orientation_5/nexus_random_0.next
